language: clojure
lein: 2.8.1
before_install:
  - cd mustard
  - lein install
  - cd ..
  - cd lein-mustard
  - lein install
  - cd ..
  - cd mustard
  - lein with-profile check deps

script:
  - lein checkall
  - lein with-profile check mustard
  - lein test